### ISSUE TITLE
Fonts load but no text shown

### ISSUE THREAD

**Issue by JorySchossau** [EriKWDev/nanim#13]
I'm just trying to run the demo code from the frontpage readme.
The debug output says the ttf font is being loaded (I had to make a fonts/ dir). But there's no text displayed.

Linux
Nim 1.6.0
nanim default nimble & head

**Comment by JorySchossau** [comment]
Turns out this is a bug in how fonts are loaded. All is fine if I make all font names specified as lowercase in the load function call. The font file has uppercase letters, but loading specifying all lowercase make loading work okay.

**Comment by EriKWDev** [comment]
Thanks for reporting and for the PR!

#15 is probably an OK fix. It stems from the fact that I make it lowercase (https://github.com/EriKWDev/nanim/blob/eb039590379d9130cecb2a94129e4dbc2b09e35f/src/nanim/core.nim#L1119) and indeed don't enforce that on the user input side.
